
name: Create XCFramework and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version number of the framework embedded in the XCFramework. This version number is also used as the release tag.'
        type: string
        required: true

jobs:
  create-xcframework-and-release-workflow:
    uses: wintermuteconsult/.github/.github/workflows/xcframework.yml@v2
    with:
      workspaceFile: llama.xcworkspace
      xcFrameworkName: llama
      scheme: llama
      sdk: '["iphoneos", "iphonesimulator", "macosx"]'
      version: ${{ inputs.version }}
      configuration: Release
      runsonlabels: '["macOS", "self-hosted"]'
      user: PaulsAutomationBot
    secrets:
      access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
